### ISSUE TITLE
Special character encoding error

### ISSUE THREAD

**Issue by rlmagnusson** [SeisComP/seiscomp#15]
Trying to set seedlink bindings where the station description contains special characters (Icelandic in this case) fails:

`seiscomp update-config seedlink`
>...
>+ network VE
>error: command 'update-config' failed: 'ascii' codec can't encode character '\xf0' in position 26: >ordinal not in range(128)

If the special characters are overwritten with basic ASCII characters the update works fine. This was not the case in previous version. Probably due to different handling of unicode between python 2 and 3.

**Comment by andres-h** [comment]
It seems that newer Python 3 does not have this issue. You can try to apply this patch: https://github.com/SeisComP/seiscomp/pull/2

It was not accepted, because it may introduce unwanted side effects, but maybe we should re-consider this.

**Comment by gempa-jabe** [comment]
I would prefer to remove the LC_ALL settings altogether and check where problems arise and why and how to solve them. I know that this setting is/was necessary to parse numbers correctly from XML with period notation and to not use the localized versions with e.g. comma. Maybe that can be made explicit in the parsing code. To display numbers and other localized strings it would be desirable to respect the users choice. That is a project on its own but I think it will be necessary at some point.
