### ISSUE TITLE
Issue running seiscomp setup

### ISSUE THREAD

**Issue by kisira** [SeisComP/seiscomp#23]
When I run seiscomp setup I get an error message. I am trying to install seiscomp on an Ubuntu 21.04 machine. I am not sure what I am doing wrong. THe exact error message is: 

Traceback (most recent call last):
  File "/home/sysop/seiscomp/bin/seiscomp-control.py", line 19, in <module>
    import seiscomp._config
ImportError: libpython3.8.so.1.0: cannot open shared object file: No such file or directory

**Comment by gempa-jabe** [comment]
Please post installation and usage issues to https://forum.seiscomp.de/.
