### ISSUE TITLE
libboost-signals1.74 does not exist in debian 11

### ISSUE THREAD

**Issue by sickel** [SeisComP/seiscomp#25]
Trying to install seiscomp on debian 11, share/deps/debian/11/install-base.sh fails: with message "could not find package libboost-signals1.74.0".

Using apt search, no libboost-signals packages does exist in debian 11. Also, signals1 does not exist in libboost 74, it has been replaced by signals2 (I do not know if this is a drop-in replacement for signals1 in seiscomp)

**Comment by andres-h** [comment]
Probably a mistake in install-base.sh. I compiled on Debian 11 and I have neither signals1 nor signals2 installed.

**Comment by gempa-jabe** [comment]
Only scqc is using boost signals2 and signals2 is header only.

**Comment by gempa-jabe** [comment]
I have remove signals from the base dependencies for Debian 11 in master.
