### ISSUE TITLE
dependencies

### ISSUE THREAD

**Issue by HerrMuellerluedenscheid** [SeisComP/seiscomp#28]
Hi,

I'm setting up an ansible role to build the seiscomp seedlink server. The README states `crypto-dev` as dependency. Is it this one? https://github.com/cryptodev-linux/cryptodev-linux

Is this the according ubuntu package? `libcrypto++-dev`

Are all the dependencies required (excluding the optional dependencies) to build and run the seedlink server plugin?

best
Marius

**Comment by gempa-jabe** [comment]
The dependency refers to libcrypto which should be available with libssl already. The Ubuntu package was actually crypto-dev I far as I remember. I don't use Ubuntu. You can leave it out and try to compile without it. If there are error messages we can check further.

> Are all the dependencies required (excluding the optional dependencies) to build and run the seedlink server plugin?

cmake-gui is actually not required. What is the Seedlink server plugin?

**Comment by andres-h** [comment]
I think he means the seedlink package.

The dependencies are gcc, cmake, flex, libxml2-dev and libssl-dev.

cmake-gui is useful for interactive compilation only.

**Comment by HerrMuellerluedenscheid** [comment]
Okay, thanks for the input!

 I started drafting it here https://github.com/HerrMuellerluedenscheid/ansible-seiscomp-seedlink
I'll keep you posted and let you know when the ansible role is ready.
