### ISSUE TITLE
seiscomp shell command add doesn't exit

### ISSUE THREAD

**Issue by HerrMuellerluedenscheid** [SeisComP/seiscomp#29]
I started the `seiscomp shell` and ran `help`. `list stations`, `list profiles seedlink` appear to work but running the indicated `add` command returns `Unknown command: add`.

```
$ add profile seedlink testprofile
Unknown command: add
```

**Comment by gempa-jabe** [comment]
`seiscomp shell` is far from being implemented completely. Some commands such as `add` is not. We should remove unsupported commands from the help page. Thank you for pointing that out.
