### ISSUE TITLE
Switching to MyST-Parser instead of m2r for compiling documentation from Markdown files

### ISSUE THREAD

**Issue by morealaz** [SeisComP/seiscomp#32]
Currently this project use python [m2r](https://github.com/miyakogi/m2r) module for compiling markdown files for documentation. But m2r is an old module which is not updated in recent years and compiling documentation is not working on newer system with updated packages which also using Python 3 as default python, like Arch Linux.
Sphinx [recommended](https://www.sphinx-doc.org/en/master/usage/markdown.html) using [MyST-Parser](https://myst-parser.readthedocs.io/en/latest/) module  for working with markdown files.
can this project switch to using MyST-Parser instead of m2r?

**Comment by gempa-dirk** [comment]
I tried the myst-parser. The markdown directives for headings
```
# header 1

## header 2
```

do not seem to be not easily recognized and formatted. Thus the MyST extension does no seem to fully support markdown.

We would need to re-write all MD documents to something like:

```
header 1
#######

header 2
------------
```

**Comment by morealaz** [comment]
@gempa-dirk : According to [myst-parser](https://myst-parser.readthedocs.io/en/latest/index.html) documentations:

> MyST is a superset of [CommonMark Markdown](https://myst-parser.readthedocs.io/en/latest/syntax/reference.html#commonmark-tokens). 
> Any CommonMark document is also MyST-compliant.

which support heading directive like:
```
# header 1

## header 2
```
which you mentioned.

It also says that:

> MyST [extends CommonMark](https://myst-parser.readthedocs.io/en/latest/syntax/reference.html#extended-block-tokens) with syntax meant for scholarly writing and technical documentation.

which support more token needed for sphinx.

**Comment by gempa-jabe** [comment]
We are discussing that with the MyST folks ...

**Comment by gempa-jabe** [comment]
What I actually forgot about was that I am using `m2r2` on my Arch as a replacement. We will check if that can serve as a replacement.

**Comment by morealaz** [comment]
Finally, I'v done a successful documentation build, using following steps:

1. In `doc/templates/conf.py`, change `m2r` in **extensions** list to `myst_parser`
2. In `doc/templates/conf.py`, change **source_suffix** list to `['.rst', '.md']`
3. In `doc/templates/index.rst`, under the **Understanding** section, change
    `/base/changelog`
to 
     `changelog </base/CHANGELOG>`
4. Add 
````
```{_sc-changelog}
```
````
to start of `CHANGELOG.md` file.

**Comment by gempa-jabe** [comment]
As have tested `m2r2` and it works as drop-in replacement we are going to use that. Much easier transition ...

**Comment by morealaz** [comment]
I'm going to stick to **MyST-Parser** for Arch Linux package, because it's package is already available in Arch repository and worked just fine.

**Comment by morealaz** [comment]
> As we have tested `m2r2` and it works as drop-in replacement we are going to use that. Much easier transition ...

If you wanted to use `MyST-Parser`, I can made necessary changes and make a pull request!!
It's not as hard as you think. just need to remove `doc/base/changelog.rst` because it's redundant.
instead of using `.. mdinclude::` directives in a `rst` files to include a markdown file, you simply just use markdown file itself.
You can add any directive to markdown files using `MyST-Parser` syntax, just like:
````
```{_sc-changelog}
```
````
which works like:
```
.. _sc-changelog:
```
in a `rst` file.

**Comment by gempa-jabe** [comment]
Thank you. We will stick to `m2r2` for now. One reason is that there is no benefit to using `MyST-Parser` right now and it will maybe break something we haven't checked yet.
