### ISSUE TITLE
errors installing scdetect and sed

### ISSUE THREAD

**Issue by AyanamiJoss** [SeisComP/seiscomp#41]
Hi! 
I am installing SeisComP using Github, so the file download is going great, only when doing the "make install" they end up generating several errors in the installation of these in "scdetect" and "sed modules"

Error in SED:

/home/sysop/seiscomp/src/extras/sed-addons/libs/seiscomp/datamodel/vs/envelopechannel.cpp: In destructor 'virtual Seiscomp::DataModel::VS::EnvelopeChannel::~EnvelopeChannel()':

/home/sysop/seiscomp/src/extras/sed-addons/libs/seiscomp/datamodel/vs/envelopech annel.cpp:78:28: error: 'compose1' is not a member of 'std' 78 | std::compose1(std::bind2nd(std::mem_fun(&EnvelopeValue::setParent),

make[2]: *** [src/extras/sed-addons/libs/seiscomp/datamodel/vs/CMakeFiles/seiscomp_datamodel_vs.dir/build.make:104: src/extras/sed-addons/libs/seiscomp/datamodel/vs/CMakeFiles/seiscomp_datamodel_vs.dir/envelopechannel.cpp.o] Error 1 make[1]: *** [CMakeFiles/Makefile2:10591: src/extras/sed-addons/libs/seiscomp/datamodel/vs/CMakeFiles/seiscomp_datamodel_vs.dir/all] Error 2 make: *** [Makefile: 166: all] Error 2

Error in scdetect:

/home/sysop/seiscomp/src/extras/scdetect/../../base/common/libs/seiscomp/logging /common.h:46:23: error: 'expect' was not declared in this scope; did you mean 'execv'?

46 | # define unlikely (x) expect((x),0)

/home/sysop/seiscomp/src/extras/scdetect/../../base/common/libs/seiscomp/logging/common.h:46:23: note: in definition of macro 'unlikely'

---

make[2]: *** [src/extras/scdetect/src/apps/cc/CMakeFiles/scdetect-cc.dir/build.m ake:76: src/extras/scdetect/src/apps/cc/CMakeFiles/scdetect-cc.dir/amplitude/factory.cpp.o] Error 1

make[1]: *** [CMakeFiles/Makefile2:10694: src/extras/scdetect/src/apps/cc/CMakeFiles/scdetect-cc.dir/all] Error 2

make: *** [Makefile: 166: all] Error 2

Solution?

**Comment by luca-s** [comment]
Hi @AyanamiJoss . You are seeing this issue because you probably tried to compile the master branch of SeisComP., which contains unreleased code. Until SeisComP 6 is out I do not plan to check the compatibility of scdetect and other SED modules against the latest SeisComP changes. However if you try to compile the branch v5 or any other released SeisComP version tag (e.g. the latest release v5.4.0) it should work. If not, please let us know.

**Comment by AyanamiJoss** [comment]
> Hi @AyanamiJoss . You are seeing this issue because you probably tried to compile the master branch of SeisComP., which contains unreleased code. Until SeisComP 6 is out I do not plan to check the compatibility of scdetect and other SED modules against the latest SeisComP changes. However if you try to compile the branch v5 or any other released SeisComP version tag (e.g. the latest release v5.4.0) it should work. If not, please let us know.

Hello, thanks for the answer, I downloaded version 5.4.0, only when installing or rather, doing the "make" command showed me a different error, any solution?
![Captura desde 2023-06-26 22-06-18](https://github.com/SeisComP/seiscomp/assets/136953526/432cdb56-e775-480c-87ea-106c6a202ae7)

**Comment by AyanamiJoss** [comment]
Hello, thanks for the answer, I downloaded version 5.4.0, only when installing or rather, doing the "make" command showed me a different error, any solution?

![Captura desde 2023-06-26 21-46-12](https://github.com/SeisComP/seiscomp/assets/136953526/26a7171d-cfd5-4c51-ab65-f861f0de1de5)

**Comment by luca-s** [comment]
The error looks suspicious because you should not have that line 27 on branch v5 of SeisComP/common. It seems the code is still on master branch. Did you `git checkout` 5.4.0 tag (or v5 branch) in ALL modules (seiscomp, common, main, seedlink, extras, sed-addons)? They all need to be consistent on the same tag or branch except scdetect

**Comment by AyanamiJoss** [comment]
> The error looks suspicious because you should not have that line 27 on branch v5 of SeisComP/common. It seems the code is still on master branch. Did you `git checkout` 5.4.0 tag (or v5 branch) in ALL modules (seiscomp, common, main, seedlink, extras, sed-addons)? They all need to be consistent on the same tag or branch (except scdetect).

ooh, thanks for your help <3, now it works

![imagen](https://github.com/SeisComP/seiscomp/assets/136953526/961ced5d-4cc1-47b5-887f-0b49584018d9)

**Comment by luca-s** [comment]
I am glad it worked. By the way, the compilation issue you found on `scdetect` is real and I will fix it when SeisComP 6 is out.
