### ISSUE TITLE
scmv map error

### ISSUE THREAD

**Issue by AyanamiJoss** [SeisComP/seiscomp#42]
Hello, I finished the installation of seiscomp5, exactly version 5.4.0, when executing "scmv" a blank map appears, any solution?
![imagen](https://github.com/SeisComP/seiscomp/assets/136953526/e3085a35-eb74-4501-a61e-a93e7239585b)

**Comment by gempa-jabe** [comment]
Hello @AyanamiJoss, this is not a user forum, please visit https://forum.seiscomp.de. There is also documentation available which covers this topic.
