### ISSUE TITLE
configuration of multiple SDS archives

### ISSUE THREAD

**Issue by petrrr** [SeisComP/seiscomp#43]
We ran into a subtile problem with the configuration of multiple SDS archives, which took us a while to understand why it would not work as expected and how to fix. 

With this issue we would like to propose a minor improvement either on the parsing of the configuration file or at least a clarification in the documentation.  We hope this would avoid confusion and frustration to others. We are refering to version 5.4.

We wanted our fdsnws dataselect service to access two SDS archives, first the consolidated/checked archive (`/mnt/fs1_archive) and second the temporary real time archive (`/mnt/fs2_archive). 

However, the following configuration, file `seiscomp/etc/fdsnws.cfg` would not have the expected result:
```
[...]
recordstream = sdsarchive:///mnt/fs1_archive,/mnt/fs2_archive
```
Only the first archive would be take into account. We understood that all after the `,` (comma) had no effect.

The solution was to use quotes:
```
[...]
recordstream = "sdsarchive:///mnt/fs1_archive,/mnt/fs2_archive"
```
But from the [documentation](https://www.seiscomp.de/doc/apps/global_recordstream.html#rs-sdsarchive) this was not obvious.

**Comment by gempa-jabe** [comment]
Thank you for the information. Actually this is partly described in https://www.seiscomp.de/doc/base/concepts/configuration.html#lists. The parser splits the parameter value by comma and only returns the fist item if an application just wants to read a string. As this is special to the encoding of values in the configuration file it does not apply specifically to the SDS archive configuration. I see your point but I am not sure how to solve it. The same applies for spaces which are compressed when not escaped or put into double quotes.

**Comment by gempa-jabe** [comment]
A [note](https://github.com/SeisComP/common/commit/405bf3e3573bd48a4a52a06d107cc613d214e524) has been added, please close this issue if that is OK for you.

**Comment by petrrr** [comment]
Thanks for considering this issue and adding the addional note. Might help avoid this trap to others.
