### ISSUE TITLE
Scanning.

### ISSUE THREAD

**Issue by aileen-fisher** [SeisComP/seiscomp#44]
Hello - we have Fortify scanned SeisComP for vulnerabilities.  If you would like a PDF copy of the result, please let me know.

**Comment by gempa-jabe** [comment]
If you want to share it, please go ahead. I hope that it covers all repositories and not just this. We would be happy to increase security and stability of the software.

**Comment by aileen-fisher** [comment]
It is only for this repository for the moment.  The report is a pdf file; where would you like me to send/attach?

**Comment by gempa-jabe** [comment]
Please send it to seiscomp-dev@gempa.de. Thank you.
