### ISSUE TITLE
Release notes for 5.5.5

### ISSUE THREAD

**Issue by luca-s** [SeisComP/seiscomp#45]
I would like to report that the [fix to MLc](https://github.com/SeisComP/common/pull/104) was not reported on the v5.5.5 release notes and since the magnitude is important I thought of reporting it.

That is important because it fixes a regression introduced in v5.5.3 by [this commit](https://github.com/SeisComP/common/commit/ad5dfa08aa70bfe1eab2c3301007e734bb2c8216).  

Before v5.5.3, when computing the magnitude using the `hypocentral` distance,  the origin depth was used as the vertical distance to the receiver, **but only if the depth was positive**.

In releases v5.5.3 and v5.5.4 the depth is always considered, 

![image](https://github.com/SeisComP/seiscomp/assets/15273575/79dad687-68a0-44c7-b42f-371bfa4bd52b)

That introduces a big difference in certain scenarios. That's why I noticed the regression and provided a fix.

I think other users should be informed about it.

**Comment by gempa-jabe** [comment]
You are right, I will add it. But I don't think that MLc is commonly used for catalogue creation.
