### ISSUE TITLE
some more preconditions for compiling missing

### ISSUE THREAD

**Issue by andhoffmann** [SeisComP/seiscomp#5]
Hi,
i'm just try to compile the new seiscomp beta on centos 8 and discovered some more dependencies need to be installed which are not mentioned on the readme.
i was necessary to install python3 development and python3 numpy packages. For the documented requirements some of the package names do differ greatly on centos8 but I was able to guess them.

Best regards
Andreas Hoffmann

**Comment by gempa-jabe** [comment]
Thank you, we will add the Python dev package dependency.
