### ISSUE TITLE
SED EEW module installation failure

### ISSUE THREAD

**Issue by AyanamiJoss** [SeisComP/seiscomp#50]
I was updating my SeisComP to version 6.0.5 along with the VS plugin, when I did the "make" command the terminal showed an error in the compilation of the "VS" plugin, I hope you can help me

![image](https://github.com/SeisComP/seiscomp/assets/136953526/ee9bc07f-c1b8-4c0e-a2e5-3dd11ecb525f)

**Comment by gempa-jabe** [comment]
This is not the correct repository to create this particular issue for. The correct repository is https://github.com/swiss-seismological-service/sed-SeisComP-contributions.git.

Make sure that you are using the correct branches or tags in every sub repository.
