### ISSUE TITLE
Scconfig shows no modules, and setup wizard give error "Setup finished with exit code 245"

### ISSUE THREAD

**Issue by dsheward-astro** [SeisComP/seiscomp#51]
I am trying to install seiscomp on macOS, however when I try to run the setup wizard I get exit code 245, and no modules show on the system tab. If I instead run scconfig with super user privileges I get error code 1.

**Comment by gempa-dirk** [comment]
SeisComP has been developed for Linux, not MacOS. If you want to compile yourself for Mac, then please read

https://docs.gempa.de/seiscomp/current/base/build.html#compiling-scname-for-macos
