### ISSUE TITLE
scautopicker is not picking any phases

### ISSUE THREAD

**Issue by Pragnath** [SeisComP/seiscomp#53]
i have installed Seiscomp6 recently and i tried to configured few global stations, the **scautopicker** (default settings) is not working, i mean it is not picking any phases. help me to solve the problem.

Thanks in advance.

![Screenshot from 2024-07-21 11-44-09](https://github.com/user-attachments/assets/45bcec1c-ff41-4aaa-83d9-b174c35cc111)

**Comment by gempa-stephan** [comment]
Please post installation and usage issues to https://forum.seiscomp.de/.
